version: '3.9'
services:
    postgres-db:
        image: postgres
        restart: always
        volumes:
            - ${PG_DATA}:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: rekjef
            POSTGRES_PASSWORD: rekjef
            POSTGRES_DB: database
        ports:
            - ${PG_PORT}:5432

    flask-api:
        build:
            context: ./api
            dockerfile: ./Dockerfile
        command: python3 -m flask run --host=0.0.0.0
        image: sale-system-api
        depends_on:
            - postgres-db
        environment:
            FLASK_APP: ${FLASK_APP}
            FLASK_ENV: ${FLASK_ENV}
            PYTHONUNBUFFERED: 1
        ports:
            - ${FLASK_PORT}:5000
        volumes:
            - ./api:/app
        
    
    react-ui:
        build:
            context: ./ui
            dockerfile: ./Dockerfile
        image: sale-system-ui
        ports:
            - ${REACT_PORT}:3000
        depends_on:
            - flask-api
            - postgres-db
        volumes:
            - ./ui:/app

volumes:
    database: