version: '3.9'
services:
   
    postgres:
        image: postgres
        restart: always
        volumes:
            - ${PG_DATA}:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: rekjef
            POSTGRES_PASSWORD: rekjef
            POSTGRES_DB: db
        ports:
            - 5432:5432

    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379

    flask:
        restart:
            always
        build:
            context: ./api
            dockerfile: ./Dockerfile
        image: sale-system-api
        depends_on:
            - postgres
            - redis
        environment:
            FLASK_APP: wsgi.py
            FLASK_ENV: development
            PYTHONUNBUFFERED: 1
        links:
            - "postgres:db"
        ports:
            - 5000:5000
        volumes:
            - ./api:/app

    react:
        build:
            context: ./ui
            dockerfile: ./Dockerfile
        image: sale-system-ui
        ports:
            - 3000:3000
        depends_on:
            - flask
        volumes:
            - ./ui:/app

volumes:
    postgres:
        driver: local