version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rekjef
      POSTGRES_PASSWORD: rekjef
      POSTGRES_DB: db
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

  flask:
    container_name: flask
    restart: always
    build:
      context: ./api
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      FLASK_APP: wsgi.py
      FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
    links:
      - "postgres:db"
    ports:
      - 5000:5000
    volumes:
      - ./api:/app

  vite-react:
    container_name: vite-react
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - flask
    links:
      - flask
    volumes:
      - ./ui:/app
      - /app/node_modules

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.yaml
    ports:
      - 80:8080

volumes:
  postgres:
    driver: local
